services:
  - type: web
    name: review-classifier
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "streamlit run app/app.py --server.address=0.0.0.0 --server.port=$PORT"
    plan: free
